name: Build-MacOS

on: workflow_dispatch

jobs:
  build-macos:
    name: macOS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        buildType: [Release]
        os: [macOS-14]
    env:
      BUILDTYPE: ${{ matrix.buildType }}
    steps:
    - name: Install automake
      run: brew install automake autoconf libtool texinfo
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Build it
      run: make VERBOSE=1
    - name: Test it
      run: make test
    - name: Test it (advanced)
      run: make test-advanced
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ matrix.buildType }}-${{ matrix.os }}
        path: ./build/*
